import Header from './components/layout/header'
import './globals.css'
import { Sora } from 'next/font/google'

const inter = Sora({ subsets: ['latin'] })

export const metadata = {
  title: 'Navbar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      
      </body>
    </html>
  )
}
